version: '3.1'
services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - 27017:27017

  mysql:
    image: mysql
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '12345'

    ports:
      - '3306:3306'
  elasticsearch:
    image: elasticsearch:8.12.0
    container_name: elasticsearch
    restart: always
    expose:
      - 9200:9200
      - 9200:9200
    environment:
      discovery.type: single-node







