server:
  port: 7201

spring:
  application:
    name: eurekaserver

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7201/eureka

  management:
    tracing:
      sampling:
        probability: 1.0
