server:
  port: 7204

spring:
  application:
    name: notificationservice
  boot:
    admin:
      client:
        url: http://localhost:7207
  rabbitmq:
    username: fotiomicroservice
    password: fotiomicroservice
    port: '5672'
    host: localhost

  datasource:
    username: postgres
    password: '12345'
    url: jdbc:postgresql://localhost:5432/TaskDB
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: 'true'
    hibernate:
      ddl-auto: update

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7201/eureka

ms:
  rabbit:
    exchange:
      name: fotioexchange
    queue:
      name: fotioqueue
    routing:
      name: fotiorouting


management:
  endpoints.web.exposure.include:
    - '*'
  tracing:
    sampling:
      probability: 1.0